version: "3"
services:
  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  db_data:
